# -*- coding: utf-8 -*-
"""FacultyPass_AI_Teacher_Recognition2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11gbagesBHwRi1S1cYonqDihqE2duxqtZ

### Install required libraries
"""

!pip install -q insightface onnxruntime opencv-python-headless scikit-learn numpy matplotlib

"""## Facial Embeddings matching

### DEPENDENCIES & MODULE IMPORTS
"""

import os
import sys
import time
import json
import pickle
import base64
import numpy as np
import cv2
from typing import List, Dict, Tuple, Optional, Any
import matplotlib.pyplot as plt

# Install required packages if missing
try:
    import insightface
except ImportError:
    print("[INFO] Installing InsightFace and required dependencies...")
    !pip install -q insightface onnxruntime opencv-python-headless scikit-learn matplotlib
    import insightface

from insightface.app import FaceAnalysis
from sklearn.metrics.pairwise import cosine_similarity
from IPython.display import display, Javascript, HTML
from google.colab.output import eval_js

print("[STATUS] All dependencies imported successfully.")

"""### CELL 2: VISION ENGINE WRAPPER (InsightFace ArcFace)

"""

class VisionEngine:
    """
    InsightFace ArcFace Model Wrapper (buffalo_l backbone).
    Extracts 512-D normalized feature embeddings and facial landmarks.
    """
    def __init__(self, name: str = 'buffalo_l', ctx_id: int = -1, det_size: Tuple[int, int] = (640, 640)):
        print(f"[INFO] Initializing InsightFace ArcFace model zoo: '{name}'...")
        # ctx_id = -1 for CPU, 0 for GPU
        self.app = FaceAnalysis(name=name, providers=['CUDAExecutionProvider', 'CPUExecutionProvider'] if ctx_id >= 0 else ['CPUExecutionProvider'])
        self.app.prepare(ctx_id=ctx_id, det_size=det_size)
        print("[STATUS] Vision Engine initialized.")

    def analyze_frame(self, frame_bgr: np.ndarray) -> List[Any]:
        """Detects faces and returns face objects with embeddings & landmarks."""
        return self.app.get(frame_bgr)


# Global Vision Engine Instance
vision_engine = VisionEngine(ctx_id=-1)

"""### CELL 3: PERSISTENT VECTOR DATABASE WITH BIOMETRIC DEDUPLICATION (5x512)

"""

import os
import pickle
import numpy as np
from typing import List, Dict, Tuple, Any, Optional
from sklearn.metrics.pairwise import cosine_similarity

# Target path next to your notebook
DB_FILEPATH = os.path.join(os.getcwd(), "faculty_vector_db.pkl")


class ProductionTeacherVectorDB:
    """
    Persistent Vector Database supporting 5x512 multi-pose matrices.
    Loads existing .pkl files without overriding old records.
    """
    def __init__(self, db_filepath: str = DB_FILEPATH, similarity_threshold: float = 0.50):
        self.filepath = db_filepath
        self.similarity_threshold = similarity_threshold
        self.db: Dict[str, Dict[str, Any]] = {}

        # Safe Load: Only loads existing data, NEVER creates a blank file on startup
        self.load_from_disk()

    def is_registered_id(self, teacher_id: str) -> bool:
        """Checks if a primary key ID already exists in DB."""
        return teacher_id in self.db

    def check_biometric_duplicate(self, new_pose_matrix: np.ndarray) -> Tuple[bool, Optional[Dict[str, Any]], float]:
        """Compares new 5x512 matrix against ALL stored matrices in DB."""
        if not self.db:
            return False, None, 0.0

        best_match_teacher = None
        highest_score = -1.0

        for existing_id, profile in self.db.items():
            stored_matrix = profile["embedding_matrix"]  # Shape: (5, 512)
            similarity_matrix = cosine_similarity(new_pose_matrix, stored_matrix)
            max_similarity = float(np.max(similarity_matrix))

            if max_similarity > highest_score:
                highest_score = max_similarity
                best_match_teacher = profile

        if highest_score >= self.similarity_threshold:
            return True, best_match_teacher, highest_score

        return False, None, highest_score

    def register_teacher_embeddings(
        self,
        teacher_id: str,
        name: str,
        department: str,
        embeddings: List[np.ndarray]
    ) -> bool:
        """
        Appends new record to memory and updates disk without losing existing records.
        """
        if len(embeddings) != 5:
            print(f"[ERROR] Registration failed for {name}: Expected 5 pose embeddings, got {len(embeddings)}.")
            return False

        normalized_poses = []
        for emb in embeddings:
            norm = np.linalg.norm(emb)
            if norm > 0:
                normalized_poses.append(emb / norm)
            else:
                normalized_poses.append(emb)

        new_pose_matrix = np.array(normalized_poses, dtype=np.float32)  # Shape: (5, 512)

        # 1. Primary Key Check
        if self.is_registered_id(teacher_id):
            print(f"[REJECTED] Primary Key Conflict: Teacher ID '{teacher_id}' already exists in DB.")
            return False

        # 2. Biometric Duplicate Check
        is_dup, matched_profile, score = self.check_biometric_duplicate(new_pose_matrix)
        if is_dup:
            print("\n" + "🚨 " * 12)
            print(f"[REGISTRATION BLOCKED] Biometric Duplicate Detected!")
            print(f" This face is already registered as: {matched_profile['name']} (ID: {matched_profile['teacher_id']})")
            print(f" Match Score: {score * 100:.2f}%")
            print("🚨 " * 12 + "\n")
            return False

        # 3. Add to local memory dictionary (preserves existing teachers)
        self.db[teacher_id] = {
            "teacher_id": teacher_id,
            "name": name,
            "department": department,
            "embedding_matrix": new_pose_matrix
        }

        # 4. Save updated dictionary to file
        self.save_to_disk()
        print(f"[SUCCESS] Registered & Saved: {name} ({teacher_id}) | Total Teachers in DB: {len(self.db)}")
        return True

    def save_to_disk(self):
        """Saves current database dictionary to disk."""
        try:
            with open(self.filepath, "wb") as f:
                pickle.dump(self.db, f)
            print(f"[DISK SAVE] Updated persistent file at: '{self.filepath}' ({len(self.db)} records saved)")
        except Exception as e:
            print(f"[ERROR] Disk save failed: {e}")

    def load_from_disk(self):
        """Loads database from .pkl file if present; otherwise leaves DB empty."""
        if os.path.exists(self.filepath):
            try:
                with open(self.filepath, "rb") as f:
                    self.db = pickle.load(f)
                print(f"[DISK LOAD] Existing file found! Loaded {len(self.db)} teacher records from '{self.filepath}'.")
            except Exception as e:
                print(f"[WARNING] Could not read database file: {e}")
                self.db = {}
        else:
            print(f"[DISK LOAD] No existing file found at '{self.filepath}'. A new file will be created upon first registration.")


# Global Persistent Instance
faculty_db = ProductionTeacherVectorDB(db_filepath=DB_FILEPATH, similarity_threshold=0.50)

"""### CELL 4: MULTI-POSE CAPTURE ENGINE WITH FACIAL LANDMARK VALIDATION

"""

def validate_pose_orientation(face: Any, target_pose: str) -> Tuple[bool, str]:
    """
    Validates head pose orientation using 5-point facial landmarks
    aligned with unmirrored frame coordinates.
    """
    if not hasattr(face, 'kps') or face.kps is None:
        return True, "Valid (No landmarks available)"

    kps = face.kps  # Landmarks: [left_eye, right_eye, nose, mouth_left, mouth_right]
    left_eye, right_eye, nose = kps[0], kps[1], kps[2]

    eye_distance = np.linalg.norm(right_eye - left_eye)
    if eye_distance == 0:
        return True, "Valid"

    eye_center = (left_eye + right_eye) / 2.0
    horizontal_offset = (nose[0] - eye_center[0]) / eye_distance
    vertical_offset = (nose[1] - eye_center[1]) / eye_distance

    if target_pose == "FRONT / CENTER":
        if abs(horizontal_offset) > 0.25:
            return False, "Please look straight at the camera."

    elif target_pose == "LOOK LEFT":
        if horizontal_offset < 0.08:
            return False, "Please turn your head slightly further to your LEFT."

    elif target_pose == "LOOK RIGHT":
        if horizontal_offset > -0.08:
            return False, "Please turn your head slightly further to your RIGHT."

    elif target_pose == "LOOK UP":
        if vertical_offset > 0.35:
            return False, "Please tilt your head slightly UPWARDS."

    elif target_pose == "LOOK DOWN":
        if vertical_offset < 0.65:
            return False, "Please tilt your head slightly DOWNWARDS."

    return True, "Pose Validated"


def capture_multipose_enrollment(teacher_id: str, name: str, department: str):
    """
    Launches browser webcam kiosk and guides user through 5 validated pose captures.
    """
    poses = ["FRONT / CENTER", "LOOK LEFT", "LOOK RIGHT", "LOOK UP", "LOOK DOWN"]
    captured_embeddings: List[np.ndarray] = []

    js_script = """
    async function startPoseEnrollment() {
        const div = document.createElement('div');
        div.style.fontFamily = 'Arial, sans-serif';
        div.style.padding = '15px';
        div.style.border = '2px solid #2B6CB0';
        div.style.borderRadius = '10px';
        div.style.backgroundColor = '#F7FAFC';
        div.style.maxWidth = '640px';

        const header = document.createElement('h3');
        header.innerText = 'FacultyPass AI — Multi-Pose Kiosk Registration';
        header.style.color = '#2B6CB0';
        header.style.marginTop = '0';
        div.appendChild(header);

        const instructions = document.createElement('p');
        instructions.id = 'pose_instruction';
        instructions.style.fontSize = '18px';
        instructions.style.fontWeight = 'bold';
        instructions.style.color = '#C53030';
        div.appendChild(instructions);

        const video = document.createElement('video');
        video.style.width = '100%';
        video.style.borderRadius = '8px';
        video.style.transform = 'scaleX(-1)';
        div.appendChild(video);

        document.body.appendChild(div);

        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        video.srcObject = stream;
        await video.play();

        window.currentCanvas = document.createElement('canvas');
        window.currentCanvas.width = video.videoWidth;
        window.currentCanvas.height = video.videoHeight;
        window.videoElem = video;
        window.streamTrack = stream.getVideoTracks()[0];
    }

    async function captureFrame() {
        const ctx = window.currentCanvas.getContext('2d');
        ctx.drawImage(window.videoElem, 0, 0);
        return window.currentCanvas.toDataURL('image/jpeg', 0.9);
    }

    async function setInstruction(text) {
        document.getElementById('pose_instruction').innerText = text;
    }

    async function stopCamera() {
        if (window.streamTrack) {
            window.streamTrack.stop();
        }
    }
    """

    display(Javascript(js_script))
    eval_js('startPoseEnrollment()')
    time.sleep(1)

    print(f"\n[ENROLLMENT] Starting multi-pose capture for: {name} ({teacher_id})")

    for idx, pose in enumerate(poses):
        pose_accepted = False

        while not pose_accepted:
            eval_js(f"setInstruction('Pose {idx+1}/5: Please {pose}')")
            input(f"Press [ENTER] once ready for Pose {idx+1} ({pose})...")

            b64_str = eval_js('captureFrame()')
            img_bytes = base64.b64decode(b64_str.split(',')[1])
            nparr = np.frombuffer(img_bytes, np.uint8)
            frame_bgr = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

            faces = vision_engine.analyze_frame(frame_bgr)
            if len(faces) == 0:
                print(f" ⚠️ No face detected for pose '{pose}'. Please try again.")
                continue

            largest_face = max(faces, key=lambda f: (f.bbox[2]-f.bbox[0]) * (f.bbox[3]-f.bbox[1]))

            is_valid, msg = validate_pose_orientation(largest_face, pose)
            if not is_valid:
                print(f" ⚠️ Pose Rejected: {msg}")
                continue

            captured_embeddings.append(largest_face.embedding)
            print(f" ✅ Pose '{pose}' validated & captured successfully.")
            pose_accepted = True

    eval_js('stopCamera()')

    # Send captured vectors to database for biometric verification & save
    faculty_db.register_teacher_embeddings(teacher_id, name, department, captured_embeddings)

"""### CELL 5: REGISTRATION CONTROLLER UI

"""

def run_teacher_registration():
    """Executes registration menu and links to persistent database."""
    print("\n=======================================================")
    print("   FACULTYPASS AI — NEW TEACHER REGISTRATION MODE     ")
    print("=======================================================\n")

    teacher_id = input("Enter Teacher ID (e.g., FAC-101): ").strip()
    if not teacher_id:
        print("[ERROR] Teacher ID cannot be empty.")
        return

    # Updated method name call: is_registered_id
    if faculty_db.is_registered_id(teacher_id):
        existing_teacher = faculty_db.db[teacher_id]
        print(f"\n[WARNING] ID '{teacher_id}' is ALREADY registered to {existing_teacher['name']}.")
        return

    name = input("Enter Teacher Full Name: ").strip()
    department = input("Enter Department: ").strip()

    if not name or not department:
        print("[ERROR] Name and Department are required.")
        return

    # Triggers capture & automatic .pkl disk saving
    capture_multipose_enrollment(teacher_id, name, department)

"""### CELL 6: IDENTIFICATION ENGINE & VISUAL ANNOTATOR

"""

def identify_teacher_from_image(
    image_bgr: np.ndarray,
    threshold: float = 0.45
) -> Tuple[np.ndarray, List[Dict[str, Any]]]:
    """Identifies live faces against stored .pkl 5x512 matrices."""
    annotated_img = image_bgr.copy()
    faces = vision_engine.analyze_frame(image_bgr)
    json_results = []
    pose_names = ["Front", "Left", "Right", "Up", "Down"]

    if len(faces) == 0:
        print("[INFO] No faces detected in input frame.")
        return annotated_img, json_results

    db_items = list(faculty_db.db.values())
    if not db_items:
        print("[WARNING] Vector Database is empty! Register a teacher first.")
        return annotated_img, json_results

    for face in faces:
        bbox = face.bbox.astype(int)

        norm = np.linalg.norm(face.embedding)
        query_vector = (face.embedding / norm).reshape(1, -1) if norm > 0 else face.embedding.reshape(1, -1)

        best_teacher = None
        max_score = -1.0
        matched_pose_idx = -1

        for item in db_items:
            # FIX: Key updated to 'embedding_matrix' matching Cell 3 schema
            teacher_matrix = item["embedding_matrix"]  # Shape: (5, 512)

            similarities = cosine_similarity(query_vector, teacher_matrix)[0]
            highest_pose_idx = int(np.argmax(similarities))
            highest_pose_score = float(similarities[highest_pose_idx])

            if highest_pose_score > max_score:
                max_score = highest_pose_score
                best_teacher = item
                matched_pose_idx = highest_pose_idx

        if max_score >= threshold:
            teacher_id = best_teacher['teacher_id']
            teacher_name = best_teacher['name']
            matched_pose = pose_names[matched_pose_idx]
            label_text = f"{teacher_name} ({max_score*100:.1f}%) [{matched_pose}]"
            box_color = (0, 255, 0)
            status = "Recognized"
        else:
            teacher_id = "N/A"
            teacher_name = "Unknown Individual"
            matched_pose = "None"
            label_text = f"Unknown ({max_score*100:.1f}%)"
            box_color = (0, 0, 255)
            status = "Unknown"

        h, w, _ = annotated_img.shape
        xmin, ymin = max(0, bbox[0]), max(0, bbox[1])
        xmax, ymax = min(w, bbox[2]), min(h, bbox[3])

        cv2.rectangle(annotated_img, (xmin, ymin), (xmax, ymax), box_color, 2)
        (text_w, text_h), _ = cv2.getTextSize(label_text, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 2)
        cv2.rectangle(annotated_img, (xmin, max(0, ymin - text_h - 10)), (xmin + text_w + 10, ymin), box_color, -1)
        cv2.putText(annotated_img, label_text, (xmin + 5, max(12, ymin - 5)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)

        json_results.append({
            "teacher_id": teacher_id,
            "name": teacher_name,
            "status": status,
            "matched_pose": matched_pose,
            "similarity_score": round(float(max_score), 4),
            "confidence_percentage": f"{max_score*100:.2f}%",
            "bbox_coordinates": {"xmin": int(xmin), "ymin": int(ymin), "xmax": int(xmax), "ymax": int(ymax)},
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S")
        })

    return annotated_img, json_results

"""### CELL 7: LIVE CHECK-IN SCANNER

"""

def display_detection_results(image_bgr: np.ndarray, results: List[Dict[str, Any]]):
    """
    Utility function to display the annotated image frame with bounding boxes
    and print formatted JSON detection logs.
    """
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(9, 5))
    plt.imshow(image_rgb)
    plt.axis("off")
    plt.title("FacultyPass AI — Camera Verification Output", fontsize=12, fontweight='bold')
    plt.show()

    print("\n================ DETECTED RESULTS SUMMARY ================")
    print(json.dumps(results, indent=2))
    print("==========================================================")


def run_live_checkin_scan():
    """
    Opens browser webcam, captures a live snapshot, and identifies
    the teacher against all database records.
    """
    js_script = """
    async function takeLiveSnapshot() {
        const div = document.createElement('div');
        div.style.fontFamily = 'Arial, sans-serif';
        div.style.padding = '15px';
        div.style.border = '2px solid #2B6CB0';
        div.style.borderRadius = '10px';
        div.style.backgroundColor = '#F7FAFC';
        div.style.maxWidth = '640px';

        const header = document.createElement('h3');
        header.innerText = 'FacultyPass AI — Live Attendance Scanner';
        header.style.color = '#2B6CB0';
        header.style.marginTop = '0';
        div.appendChild(header);

        const video = document.createElement('video');
        video.style.width = '100%';
        video.style.borderRadius = '8px';
        video.style.transform = 'scaleX(-1)';
        div.appendChild(video);

        const btn = document.createElement('button');
        btn.innerText = '📸 Scan Face for Check-In';
        btn.style.marginTop = '10px';
        btn.style.padding = '10px 20px';
        btn.style.fontSize = '16px';
        btn.style.backgroundColor = '#2F855A';
        btn.style.color = 'white';
        btn.style.border = 'none';
        btn.style.borderRadius = '5px';
        btn.style.cursor = 'pointer';
        div.appendChild(btn);

        document.body.appendChild(div);

        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        video.srcObject = stream;
        await video.play();

        return new Promise((resolve) => {
            btn.onclick = () => {
                const canvas = document.createElement('canvas');
                canvas.width = video.videoWidth;
                canvas.height = video.videoHeight;
                canvas.getContext('2d').drawImage(video, 0, 0);
                stream.getVideoTracks()[0].stop();
                div.remove();
                resolve(canvas.toDataURL('image/jpeg', 0.9));
            };
        });
    }
    """
    display(Javascript(js_script))
    print("[INFO] Click '📸 Scan Face for Check-In' in the window below...")

    b64_str = eval_js('takeLiveSnapshot()')
    img_bytes = base64.b64decode(b64_str.split(',')[1])
    nparr = np.frombuffer(img_bytes, np.uint8)
    frame_bgr = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

    annotated_img, results = identify_teacher_from_image(frame_bgr, threshold=0.45)
    display_detection_results(annotated_img, results)

"""### CELL 8A: EXECUTION — TEACHER REGISTRATION MODE

"""

print("\n=======================================================")
print(" 🚀 FACULTYPASS AI — NEW TEACHER REGISTRATION KIOSK")
print("=======================================================\n")

# Run the registration flow
run_teacher_registration()

"""### CELL 8B: EXECUTION — LIVE ATTENDANCE CHECK-IN SCANNER

"""

print("\n=======================================================")
print(" 📸 FACULTYPASS AI — LIVE ATTENDANCE CHECK-IN SCANNER")
print("=======================================================\n")

# Run the live verification flow
run_live_checkin_scan()

"""### Display all registered members"""

# Helper code to check database count and display all registered members
registered_teachers = faculty_db.db

print("=======================================================")
print(f" TOTAL REGISTERED MEMBERS IN DATABASE: {len(registered_teachers)}")
print("=======================================================\n")

if not registered_teachers:
    print("[INFO] The vector database is currently empty.")
else:
    for idx, (t_id, record) in enumerate(registered_teachers.items(), 1):
        print(f" {idx}. ID: {record['teacher_id']} | Name: {record['name']} | Dept: {record['department']}")

print("\n=======================================================")

"""### Remove all users from the Database"""

import getpass

def clear_database_with_password():
    print("=======================================================")
    print("       FACULTYPASS AI — DANGER ZONE: PURGE DB          ")
    print("=======================================================\n")

    # Prompt user for password
    # Note: If running in standard terminal/Colab, input() works cleanly
    user_input_pass = input("🔑 Enter Admin Password to confirm purge: ").strip()

    # Password Verification Check
    if user_input_pass == ADMIN_PASSWORD:
        print("\n🔓 Password verified successfully!")

        # 1. Clear In-Memory Vector Database
        faculty_db.db.clear()

        # 2. Clear Attendance Logs
        if "ATTENDANCE_LOGS" in globals():
            ATTENDANCE_LOGS.clear()

        print("\n=======================================================")
        print(" ✅ ALL FACULTY MEMBERS & LOGS REMOVED FROM MEMORY")
        print(f" 📊 TOTAL REGISTERED MEMBERS NOW: {len(faculty_db.db)}")
        print("=======================================================\n")
    else:
        print("\n❌ ACCESS DENIED: Incorrect password!")
        print("🔒 Database purge aborted. Users remain safe in memory.")
        print("=======================================================\n")


# Execute Purge Command
clear_database_with_password()